SELECT CATEGORY1,
	CATEGORY2,
	--CATEGORY3,
	--CATEGORY4,
	SUM(TOTALPRICE) AS [TOTAL PRICE],
	COUNT(*) AS [ROW COUNT],
	SUM(AMOUNT) AS [TOTAL AMOUNT]

FROM SALES
GROUP BY CATEGORY1,CATEGORY2--,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2--,CATEGORY3,CATEGORY4