SELECT CITY,
	COUNT(DISTINCT CUSTOMERNAME) AS [MÜÞTERÝ SAYISI],
	COUNT(DISTINCT FICHENO) AS [ALIÞVERÝÞ SAYISI],
	COUNT(*) AS [ÜRÜN SAYISI] FROM SALES
WHERE MONTHNAME_ = '01.OCAK'
GROUP BY CITY
ORDER BY CITY