SELECT CITY,
	SUM(TOTALPRICE) AS [TOTAL PRICE],
	COUNT(DISTINCT CUSTOMERNAME) AS [CUSTOMER COUNT]
FROM SALES
--WHERE CITY IN('ÝSTANBUL','ANKARA','ÝZMÝR','AYDIN','HATAY')
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000 
--HAVING COUNT(DISTINCT CUSTOMERNAME)>2000 AND SUM(TOTALPRICE)>40000 
ORDER BY SUM(TOTALPRICE) DESC